version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: task-management-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: task_management_system
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dev

volumes:
  mysql_data:
networks:
  